sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Sk5N6v6UXeQbQlICv92HxWwLTNllrYKldLaSQli2hHzFhA5lfUeifEt4jSbLn0bS3U3kD+AKeO3ou7F2aqcjR7Ce57iejY8fLIcH7hE/Ktzc0Yu0hjE8+0ZeIm/2pev0uNgYad9QgU3gIhQFP04tCIiWTTooswa129PIxip+vui+ZifvW3CqnNci/pKypzUm6b6GYbcDhGE8jqeeSGlLjXPGYM9aMdJBdfSZnT1VguSoyfDegPyJDGL2+Y6T7fVP7NcImHxklhDvQrZ0N/RlV2HDp2dZNtgoVHxFXsiHb7gvZhyMAcZcnL96ddxSWdVxIFVOlYbYYk5hHGH8iatnHBOVGJwGz1jfMO9EWuBpkaQyM/qt9VDtO+rxzb2MxulRrS0aIsLN//U++Xi/IWsWj+vU5l1/Zv0BGy4QL9gaDuNEMCpSjWqkxw3W3byvB1leChL0gtyDYj3zcMQMACH5JmEo0kWyhKZ8R+WrVdNo4izXIGtVVmWRrGibRiLUysvYc26yrpZ2HUjzMQT+/Vyd0Fxd7J3FJ9mdHEx6CchdBE4oV4MjDzHOjdMU1LpLY1dF/6YqvsFkwCHOi72oKCXZrb5iW6en6eLwW5h1gkB/T/Opp47G7prBqP7QNNLsT/QqYr4yslTKRE6TSD50wZy8t7SxWdxxQQmtJUauH4PDQ0E=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Rainbow-Trail_5067
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy